language: ruby
sudo: false
cache: bundler

rvm:
  - 2.3.0

services:
  - postgresql

install:
  - bundle install --jobs=3 --retry=3 --without production

before_script:
  - psql -c 'create database kudo_o_matic_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate

script:
  - bundle exec rake test

notifications:
  email: false

